# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chatbot_pb2 as chatbot__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chatbot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatbotServiceStub(object):
    """Chatbot service with streaming support
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.stream_stream(
                '/chatbot.ChatbotService/StreamChat',
                request_serializer=chatbot__pb2.ChatMessage.SerializeToString,
                response_deserializer=chatbot__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ProcessQuery = channel.unary_unary(
                '/chatbot.ChatbotService/ProcessQuery',
                request_serializer=chatbot__pb2.ChatMessage.SerializeToString,
                response_deserializer=chatbot__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetAvailableTools = channel.unary_unary(
                '/chatbot.ChatbotService/GetAvailableTools',
                request_serializer=chatbot__pb2.Empty.SerializeToString,
                response_deserializer=chatbot__pb2.ToolsResponse.FromString,
                _registered_method=True)


class ChatbotServiceServicer(object):
    """Chatbot service with streaming support
    """

    def StreamChat(self, request_iterator, context):
        """Stream chat messages for real-time conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessQuery(self, request, context):
        """Single request/response for simple queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableTools(self, request, context):
        """Get available tools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=chatbot__pb2.ChatMessage.FromString,
                    response_serializer=chatbot__pb2.ChatResponse.SerializeToString,
            ),
            'ProcessQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessQuery,
                    request_deserializer=chatbot__pb2.ChatMessage.FromString,
                    response_serializer=chatbot__pb2.ChatResponse.SerializeToString,
            ),
            'GetAvailableTools': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableTools,
                    request_deserializer=chatbot__pb2.Empty.FromString,
                    response_serializer=chatbot__pb2.ToolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.ChatbotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatbot.ChatbotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatbotService(object):
    """Chatbot service with streaming support
    """

    @staticmethod
    def StreamChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/chatbot.ChatbotService/StreamChat',
            chatbot__pb2.ChatMessage.SerializeToString,
            chatbot__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/ProcessQuery',
            chatbot__pb2.ChatMessage.SerializeToString,
            chatbot__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/GetAvailableTools',
            chatbot__pb2.Empty.SerializeToString,
            chatbot__pb2.ToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
